### ISSUE TITLE
Export Optimization

### ISSUE THREAD

**Issue by Eddith** [barancanatbas/nodejs-todoapp#2]
For optimization of Export, try the method in the image below.

![image](https://user-images.githubusercontent.com/34556282/166881713-4fe389d5-ce9b-4100-8818-59cf9ae16d47.png)

**Comment by Eddith** [comment]
"@types/express": "^4.17.13",
"@types/node": "^17.0.21",

node.js import settings to add to package.json devDependencies for import event
:fire:

**Comment by barancanatbas** [comment]
Thank you bro, I didn't know as I am new to node js.
